################################################################
# o-o                    o        o o     o--o        o     o  #
#|                       |        | |     |    o      |     |  #
# o-o  o-o  o-o o   o   oO-o   oo | |     O-o    o--o O--o -o- #
#    | |  | | |  \ / \ / |  | | | | |     |    | |  | |  |  |  #
#o--o  o  o o-o   o   o  o-o  o-o-o o     o    | o--O o  o  o  #
#                                                   |          #
#                                                o--o          #
#  o-o           o-o                                           #
# /              |  o                                          #
#O     o-o o-o  -O-   o--o                                     #
# \    | | |  |  |  | |  |                                     #
#  o-o o-o o  o  o  | o--O                                     #
#                        |                                     #
#                     o--o                                     #
################################################################

#Like the new design at the top? Ascii RULEZ BRO